### ISSUE TITLE
Get this working

### ISSUE THREAD

**Issue by choldgraf** [binder-examples/python2_with_3#1]
This seems like it should work, but it doesn't for some reason. It installs `environment.yml`, then it creates a new environment per the `postBuild` commands, but it errors when it hits `source activate python2`:
saying that `source` is not available.

the build actually succeeds, but the python2 kernel isn't available to the notebook.

@yuvipanda and @mgeier maybe we can figure this out here

**Comment by betatim** [comment]
This might be because there are restrictions on what you can list in the `postBuild`. The docker `CMD` ends up being executed as `/bin/bash -c "your stuff here"` (or similar). I kept running into this when trying to redirect output in a for loop in `postBuild`. I can't find my links from when I investigated this last, but maybe this gets you pointed in the right direction.

**Comment by choldgraf** [comment]
This now works!

**Comment by betatim** [comment]
For the historians amongst us: what was the solution/commit/PR that fixed it?

**Comment by choldgraf** [comment]
the magical incantation is:

when `runtime.txt` is used, it actually installs python 2 *alongside* python 3. So you'd get both kernels. No need to manually install them with postBuild etc. The main gotcha is that installing to python 3 is done with `requirements3.txt`, which is technically documented though I had forgotten about it. I think it's fairly unintuitive, but hopefully we can capture this with some documentation...
